import hashlib
import sys
import os.path
import time
from datetime import datetime

fileChunkSize = 1024 * 1024
# fileChunkSize = 500

def calcHash(fileName):
    # Ref: https://www.guru99.com/reading-and-writing-files-in-python.html
    f = open(fileName, "rb")
    hasher = hashlib.md5()
    hasher.update(f.read())
    hash = hasher.hexdigest()
    return hash

# Ref: https://stackoverflow.com/questions/9181859/getting-percentage-complete-of-an-md5-checksum
def calcHashWithProgress(fileName):
    readSize = 0
    prevPercent = 0
    hasher = hashlib.md5()
    totalSize = os.path.getsize(fileName)

    data = True
    f = open(fileName, "rb")

    while data:
        # Read and update digest.
        data = f.read(fileChunkSize)
        readSize += len(data)
        hasher.update(data)

        # Calculate progress.
        percent = int(1000 * readSize / totalSize)

        # Ref: https://www.pythoncentral.io/pythons-time-sleep-pause-wait-sleep-stop-your-code/
        # time.sleep(1)

        if percent > prevPercent:
            # Ref: https://stackoverflow.com/a/3395158/13441
            print ('{0}.{1}% done ({2:,d} bytes)\r'.format(int(percent / 10), int(percent % 10), readSize), end="")
            prevPercent = percent
    f.close()
    print ('                                                                      \r', end="") # Clear line
    return hasher.hexdigest()

def getOutputFileName(inputFileName):
    outputFileName = inputFileName + ".md5"
    if ("hashFileNameOutputPostfix" in cmdLineArgs):
        if (len(cmdLineArgs["hashFileNameOutputPostfix"]) > 1):
            raise Exception("-hashFileNameOutputPostfix can be specified once only")
        outputFileName += "." + cmdLineArgs["hashFileNameOutputPostfix"][0]
    return outputFileName

# Ref: https://www.pythonforbeginners.com/system/python-sys-argv
def parseCommandLine():
    global cmdLineArgs;

    # Ref: https://www.w3schools.com/python/python_dictionaries.asp
    cmdLineArgs = {
        "exec": [sys.argv[0]]
    }
    argName = ""
    # Ref: "python command line arguments in main, skip script name" https://stackoverflow.com/a/19016716/13441
    for curArg in sys.argv[1:]:
        if (argName == ""):
            argName = curArg
            if (argName[0] != "-"):
                # Ref: "Manually raising (throwing) an exception in Python" https://stackoverflow.com/questions/2052390/manually-raising-throwing-an-exception-in-python
                raise Exception("Command line argument should start with dash (-): " + argName)
            # Ref: https://stackoverflow.com/questions/4945548/remove-the-first-character-of-a-string
            argName = argName[1:]
            if (argName == ""):
                raise Exception("Invalid command line parameter '-'")
        else:
            if (argName in cmdLineArgs):
                cmdLineArgs[argName].append(curArg)
            else:
                cmdLineArgs[argName] = [curArg]
            argName = ""

    # Debug. Output parsed command line
    for argName, argValue in cmdLineArgs.items():
        argValueStr = ", ".join(argValue)
        print('// ' + argName + ' -> ' + argValueStr)

def getCurrentTimeStr():
    return datetime.now().strftime("%Y.%m.%d %H:%M:%S")

def handleInputFile(inputFileName):
    print("Handle file start time: " + getCurrentTimeStr() + " (" + inputFileName + ")")
    outputFileName = getOutputFileName(inputFileName)
    # Ref: https://stackoverflow.com/questions/82831/how-do-i-check-whether-a-file-exists-without-exceptions
    if (os.path.exists(outputFileName)):
        print("Output file name '" + outputFileName + "' exists ... calculation of hash skipped.")
        return
    print("Calculate hash for file '" + inputFileName + "'...")
    # hash = calcHash(inputFileName)
    hash = calcHashWithProgress(inputFileName)

    # Ref: https://stackoverflow.com/questions/6159900/correct-way-to-write-line-to-file
    with open(outputFileName, 'a') as outputFile:
        # outputFile.write("# MD5 hash generated by smart_hasher\n\n")
        outputFile.write(hash + " *" + inputFileName)

    print("HASH: ", hash, "(" + outputFileName + ")")
    print("Handle file end time: " + getCurrentTimeStr() + " (" + inputFileName + ")")

try:
    parseCommandLine()

    if (not "inputFile" in cmdLineArgs):
        print ("Input file(s) is not specified")
        exit()
   
    for inputFileName in cmdLineArgs["inputFile"]:
        handleInputFile(inputFileName)

except Exception as ex:
    print("Exception thrown:\n", ex)
