import hashlib
import sys
import os.path

# Ref: https://stackoverflow.com/questions/9181859/getting-percentage-complete-of-an-md5-checksum
def calcHash(fileName):
    # Ref: https://www.guru99.com/reading-and-writing-files-in-python.html
    f = open(fileName, "rb")
    m = hashlib.md5()
    m.update(f.read())
    hash = m.hexdigest()
    return hash

def getOutputFileName(inputFileName):
    outputFileName = inputFileName + ".md5"
    if ("hashFileNameOutputPostfix" in cmdLineArgs):
        if (len(cmdLineArgs["hashFileNameOutputPostfix"]) > 1):
            raise Exception("-hashFileNameOutputPostfix can be specified once only")
        outputFileName += "." + cmdLineArgs["hashFileNameOutputPostfix"][0]
    return outputFileName

# Ref: https://www.pythonforbeginners.com/system/python-sys-argv
def parseCommandLine():
    global cmdLineArgs;

    # Ref: https://www.w3schools.com/python/python_dictionaries.asp
    cmdLineArgs = {
        "exec": [sys.argv[0]]
    }
    argName = ""
    # Ref: "python command line arguments in main, skip script name" https://stackoverflow.com/a/19016716/13441
    for curArg in sys.argv[1:]:
        if (argName == ""):
            argName = curArg
            if (argName[0] != "-"):
                # Ref: "Manually raising (throwing) an exception in Python" https://stackoverflow.com/questions/2052390/manually-raising-throwing-an-exception-in-python
                raise Exception("Command line argument should start with dash (-): " + argName)
            # Ref: https://stackoverflow.com/questions/4945548/remove-the-first-character-of-a-string
            argName = argName[1:]
            if (argName == ""):
                raise Exception("Invalid command line parameter '-'")
        else:
            if (argName in cmdLineArgs):
                cmdLineArgs[argName].append(curArg)
            else:
                cmdLineArgs[argName] = [curArg]
            argName = ""

    # Debug. Output parsed command line
    for argName, argValue in cmdLineArgs.items():
        argValueStr = ", ".join(argValue)
        print(argName + " -> " + argValueStr)
try:
    parseCommandLine()

    if (not "inputFile" in cmdLineArgs):
        print ("Input file(s) is not specified")
        exit()
   
    for inputFileName in cmdLineArgs["inputFile"]:
        outputFileName = getOutputFileName(inputFileName)
        # Ref: https://stackoverflow.com/questions/82831/how-do-i-check-whether-a-file-exists-without-exceptions
        if (os.path.exists(outputFileName)):
            print("Output file name '" + outputFileName + "' exists ... calculation of hash skipped.")
            continue;
        print("Calculate hash for file '" + inputFileName + "'...")
        hash = calcHash(inputFileName)
        print("done")

        # Ref: https://stackoverflow.com/questions/6159900/correct-way-to-write-line-to-file
        with open(outputFileName, 'a') as outputFile:
            outputFile.write("# MD5 hash generated by smart_hasher\n\n")
            outputFile.write(hash + " *" + inputFileName)

        print("HASH: ", hash, "(" + outputFileName + ")")

except Exception as ex:
    print("Exception thrown:\n", ex)
